import type { WordInput } from "./types";
import { makeWord } from "./utils";

const w = (
  english: string,
  bangla: string,
  pos: string,
  example: string,
): WordInput => ({ english, bangla, pos, example, tags: ["gre500"] });

/**
 * An original, independently compiled list of ~500 advanced
 * (GRE/IELTS-level) English words with Bangla meanings. Not sourced
 * from, or a copy of, any single published word list.
 */
export const GRE_500: WordInput[] = [
  w("abate", "কমে যাওয়া, প্রশমিত হওয়া", "verb", "The storm began to abate by early morning."),
  w("aberrant", "স্বাভাবিক থেকে বিচ্যুত", "adjective", "His aberrant behavior worried his colleagues."),
  w("abeyance", "সাময়িক স্থগিতাবস্থা", "noun", "The project was held in abeyance until funding arrived."),
  w("abscond", "গোপনে পালিয়ে যাওয়া", "verb", "The clerk absconded with the company funds."),
  w("abstain", "বিরত থাকা", "verb", "She chose to abstain from voting on the issue."),
  w("abstruse", "দুর্বোধ্য", "adjective", "The lecture was too abstruse for first-year students."),
  w("accolade", "প্রশংসা, সম্মাননা", "noun", "The novel received accolades from every major critic."),
  w("acerbic", "তীক্ষ্ণ, কটু", "adjective", "His acerbic remarks left the room in silence."),
  w("acquiesce", "নীরবে সম্মত হওয়া", "verb", "She acquiesced to her manager's request without complaint."),
  w("acrimony", "তিক্ততা", "noun", "Years of acrimony had damaged the two families' friendship."),
  w("acumen", "তীক্ষ্ণ বুদ্ধি, দক্ষতা", "noun", "Her business acumen helped the company survive the crisis."),
  w("adamant", "অনড়, দৃঢ়প্রতিজ্ঞ", "adjective", "He remained adamant that he would not change his plan."),
  w("admonish", "সতর্ক করা, তিরস্কার করা", "verb", "The teacher admonished the students for being late again."),
  w("adroit", "নিপুণ, দক্ষ", "adjective", "She gave an adroit answer to a very tricky question."),
  w("adulterate", "ভেজাল মেশানো", "verb", "It is illegal to adulterate food with harmful chemicals."),
  w("aesthetic", "নান্দনিক", "adjective", "The building's aesthetic appeal drew visitors from far away."),
  w("affable", "মিশুক, সদালাপী", "adjective", "The new manager was affable and easy to talk to."),
  w("aggrandize", "গুরুত্ব বা ক্ষমতা বাড়ানো", "verb", "He used the ceremony to aggrandize his own achievements."),
  w("alacrity", "উৎসাহ, তৎপরতা", "noun", "The volunteers responded to the call with great alacrity."),
  w("allay", "প্রশমিত করা, কমানো", "verb", "The doctor's explanation helped allay her fears."),
  w("alleviate", "লাঘব করা", "verb", "The new medicine helped alleviate his chronic pain."),
  w("aloof", "উদাসীন, দূরত্ব বজায় রাখা", "adjective", "He stayed aloof from the office politics."),
  w("altruism", "পরার্থপরতা", "noun", "Her altruism was evident in years of unpaid volunteer work."),
  w("ambiguous", "দ্ব্যর্থবোধক, অস্পষ্ট", "adjective", "The contract's wording was ambiguous and led to a dispute."),
  w("ambivalent", "দ্বিধাগ্রস্ত", "adjective", "She felt ambivalent about accepting the job offer."),
  w("ameliorate", "উন্নত করা", "verb", "New policies were introduced to ameliorate working conditions."),
  w("amenable", "সম্মতিপ্রবণ, নমনীয়", "adjective", "He was amenable to changing the meeting time."),
  w("amiable", "সৌহার্দ্যপূর্ণ", "adjective", "Their amiable host made everyone feel welcome."),
  w("amorphous", "নির্দিষ্ট আকারহীন", "adjective", "The group had an amorphous structure with no clear leader."),
  w("anachronism", "কালবিরোধ, সময়ের সাথে অসামঞ্জস্যপূর্ণ জিনিস", "noun", "A typewriter in a modern office feels like an anachronism."),
  w("analogous", "সাদৃশ্যপূর্ণ", "adjective", "The heart's function is analogous to a mechanical pump."),
  w("anarchy", "বিশৃঙ্খলা, রাজনৈতিক অরাজকতা", "noun", "The sudden collapse of government led to anarchy."),
  w("anecdote", "ছোট গল্প, কিস্সা", "noun", "He opened his speech with a funny anecdote."),
  w("animosity", "শত্রুতা, বিদ্বেষ", "noun", "Old animosity between the two clans never fully faded."),
  w("anomaly", "ব্যতিক্রম, অস্বাভাবিকতা", "noun", "The scientist noticed an anomaly in the data set."),
  w("antagonist", "প্রতিপক্ষ, বিরোধী", "noun", "The novel's antagonist is far more interesting than its hero."),
  w("antipathy", "গভীর অপছন্দ", "noun", "He felt a strong antipathy toward dishonest people."),
  w("apathy", "উদাসীনতা, নিরাসক্তি", "noun", "Voter apathy resulted in a very low turnout."),
  w("appease", "শান্ত করা, তুষ্ট করা", "verb", "The government tried to appease the protesters with new promises."),
  w("apprehensive", "উদ্বিগ্ন, শঙ্কিত", "adjective", "She felt apprehensive before her first flight."),
  w("arbitrary", "খেয়ালখুশিমতো, যুক্তিহীন", "adjective", "The rule seemed arbitrary and was never explained."),
  w("arcane", "রহস্যময়, দুর্বোধ্য", "adjective", "The old manual was full of arcane technical terms."),
  w("ardent", "প্রবল আগ্রহী, উৎসাহী", "adjective", "He is an ardent supporter of the local football club."),
  w("arduous", "কষ্টসাধ্য, পরিশ্রমসাধ্য", "adjective", "The arduous climb took nearly ten hours."),
  w("articulate", "সুস্পষ্টভাবে প্রকাশ করা / বাগ্মী", "adjective", "She is an articulate speaker who explains ideas clearly."),
  w("ascetic", "কৃচ্ছ্রসাধক, ভোগবিলাসবর্জিত", "adjective", "The monk led an ascetic life in the mountains."),
  w("aspersion", "কলঙ্ক আরোপ, নিন্দা", "noun", "He cast aspersions on his rival's honesty."),
  w("assiduous", "অধ্যবসায়ী, পরিশ্রমী", "adjective", "Her assiduous preparation paid off in the final exam."),
  w("astute", "তীক্ষ্ণবুদ্ধিসম্পন্ন, চতুর", "adjective", "The astute investor spotted the risk early."),
  w("atrophy", "ক্ষয় হওয়া, শুকিয়ে যাওয়া", "verb", "Muscles can atrophy quickly without regular use."),
  w("audacious", "দুঃসাহসী", "adjective", "The team pulled off an audacious comeback in the final minutes."),
  w("augment", "বৃদ্ধি করা", "verb", "He took a second job to augment his income."),
  w("austere", "কঠোর, সাদামাটা", "adjective", "The room was austere, with only a bed and a desk."),
  w("avarice", "লোভ, ধনলিপ্সা", "noun", "Avarice slowly corrupted the once-honest official."),
  w("aver", "দৃঢ়ভাবে বলা, দাবি করা", "verb", "The witness averred that she saw the whole incident."),
  w("avert", "প্রতিরোধ করা, এড়ানো", "verb", "Quick thinking helped avert a serious accident."),
  w("awry", "ভুলপথে, এলোমেলো", "adjective", "Their carefully laid plans went awry at the last moment."),
  w("banal", "গতানুগতিক, সাধারণ", "adjective", "The film's dialogue felt banal and predictable."),
  w("baneful", "ক্ষতিকর", "adjective", "Gossip can have a baneful effect on friendships."),
  w("beguile", "মোহিত করা, প্রতারণা করা", "verb", "His charm beguiled everyone at the party."),
  w("belie", "মিথ্যা প্রমাণ করা, বিভ্রান্ত করা", "verb", "Her calm face belied the panic she felt inside."),
  w("belligerent", "যুদ্ধংদেহী, আক্রমণাত্মক", "adjective", "The customer became belligerent when refused a refund."),
  w("benevolent", "দয়ালু, পরোপকারী", "adjective", "The benevolent donor funded the entire school project."),
  w("benign", "নিরাপদ, দয়ালু, ক্ষতিকর নয়", "adjective", "The tumor turned out to be benign."),
  w("bequeath", "উইল করে দেওয়া, দান করা", "verb", "She bequeathed her library to the local university."),
  w("berate", "কঠোরভাবে বকা", "verb", "He berated his assistant for the small mistake."),
  w("bereft", "বঞ্চিত, শূন্য", "adjective", "The village was left bereft of young workers after the migration."),
  w("blasphemy", "ধর্মনিন্দা", "noun", "In that era, such statements were treated as blasphemy."),
  w("blatant", "স্পষ্ট, প্রকট", "adjective", "It was a blatant violation of the rules."),
  w("bolster", "শক্তিশালী করা, সমর্থন দেওয়া", "verb", "New evidence helped bolster the lawyer's case."),
  w("bombastic", "আড়ম্বরপূর্ণ, অতিরঞ্জিত ভাষায় পূর্ণ", "adjective", "The politician's bombastic speech impressed no one."),
  w("boorish", "অভদ্র, রুচিহীন", "adjective", "His boorish manners embarrassed the whole table."),
  w("bourgeois", "মধ্যবিত্ত শ্রেণির", "adjective", "The novel satirizes bourgeois values of the period."),
  w("brazen", "নির্লজ্জ, ঔদ্ধত্যপূর্ণ", "adjective", "It was a brazen attempt to cheat the system."),
  w("brevity", "সংক্ষিপ্ততা", "noun", "The editor praised the brevity of her report."),
  w("brusque", "রুক্ষ, সংক্ষিপ্ত ও রূঢ়", "adjective", "His brusque reply surprised the new intern."),
  w("bucolic", "গ্রাম্য, পল্লীময়", "adjective", "They spent the summer in a bucolic village."),
  w("buttress", "শক্তিশালী করা, সমর্থন করা", "verb", "New data was used to buttress the original theory."),
  w("cacophony", "কর্কশ শব্দ, বিসদৃশ শব্দসমষ্টি", "noun", "The cacophony of car horns filled the street."),
  w("cajole", "মিষ্টি কথায় রাজি করানো", "verb", "She cajoled her brother into helping with the move."),
  w("callous", "নির্মম, সংবেদনশূন্য", "adjective", "His callous remark hurt everyone in the room."),
  w("candor", "স্পষ্টবাদিতা, অকপটতা", "noun", "The manager spoke with unusual candor about the layoffs."),
  w("capitulate", "আত্মসমর্পণ করা, হার মানা", "verb", "After a long siege, the city finally capitulated."),
  w("capricious", "খামখেয়ালি, অনিশ্চিত মেজাজের", "adjective", "The weather in the hills is famously capricious."),
  w("castigate", "কঠোরভাবে সমালোচনা করা", "verb", "The critic castigated the film for its weak script."),
  w("catalyst", "উদ্দীপক, প্রভাবক", "noun", "The scandal acted as a catalyst for reform."),
  w("caustic", "তীব্র সমালোচনামূলক, দাহক", "adjective", "Her caustic wit made the interview memorable."),
  w("cavalier", "উদাসীন, তুচ্ছ জ্ঞান করা", "adjective", "He took a cavalier attitude toward the safety rules."),
  w("censure", "নিন্দা করা, তিরস্কার", "verb", "The board voted to censure the director's conduct."),
  w("chagrin", "বিরক্তি, অপ্রস্তুততা", "noun", "Much to her chagrin, the flight was delayed again."),
  w("charlatan", "ভণ্ড, প্রতারক", "noun", "The self-styled healer turned out to be a charlatan."),
  w("chicanery", "প্রতারণা, ছলচাতুরী", "noun", "The deal collapsed once the chicanery was exposed."),
  w("chimerical", "কাল্পনিক, অলীক", "adjective", "His plan to become rich overnight was purely chimerical."),
  w("churlish", "রূঢ়, অভদ্র", "adjective", "It would be churlish to refuse such a kind invitation."),
  w("circuitous", "ঘুরপথের, প্যাঁচানো", "adjective", "We took a circuitous route to avoid the traffic."),
  w("circumspect", "সতর্ক, বিচক্ষণ", "adjective", "She remained circumspect when discussing the merger."),
  w("clandestine", "গোপন, লুকানো", "adjective", "They held a clandestine meeting late at night."),
  w("clemency", "দয়া, ক্ষমা", "noun", "The judge showed clemency given his young age."),
  w("coalesce", "একত্র হওয়া, মিলিত হওয়া", "verb", "Several small groups coalesced into one movement."),
  w("coerce", "জোর করে বাধ্য করা", "verb", "No one can coerce you into signing that document."),
  w("cogent", "যুক্তিসঙ্গত, প্রবল", "adjective", "She presented a cogent argument for the new policy."),
  w("commensurate", "সমানুপাতিক", "adjective", "His salary was commensurate with his experience."),
  w("complacent", "আত্মতুষ্ট, নিশ্চিন্ত", "adjective", "The team grew complacent after their early lead."),
  w("compliant", "বাধ্য, নিয়মমাফিক", "adjective", "The new building is fully compliant with fire codes."),
  w("conciliatory", "সমঝোতামূলক", "adjective", "He offered a conciliatory tone after the argument."),
  w("concise", "সংক্ষিপ্ত ও স্পষ্ট", "adjective", "Her concise summary saved the committee a lot of time."),
  w("condone", "মেনে নেওয়া, উপেক্ষা করা", "verb", "The school will not condone any form of bullying."),
  w("conflagration", "বিরাট অগ্নিকাণ্ড", "noun", "A single spark caused a massive conflagration."),
  w("congenial", "সহৃদয়, মানানসই", "adjective", "The office has a congenial atmosphere for new employees."),
  w("conjecture", "অনুমান, ধারণা", "noun", "Without proof, his theory remained mere conjecture."),
  w("connoisseur", "রসজ্ঞ, বিশেষজ্ঞ", "noun", "She is a true connoisseur of classical music."),
  w("contentious", "বিতর্কিত", "adjective", "Immigration remains a contentious political topic."),
  w("contrite", "অনুতপ্ত", "adjective", "He gave a contrite apology after realizing his mistake."),
  w("conundrum", "জটিল সমস্যা, ধাঁধা", "noun", "The budget cuts posed a real conundrum for the school."),
  w("convivial", "আনন্দমুখর, সামাজিক", "adjective", "The dinner had a warm, convivial atmosphere."),
  w("copious", "প্রচুর", "adjective", "She took copious notes during the lecture."),
  w("corroborate", "সমর্থন করা, সত্যতা প্রমাণ করা", "verb", "New witnesses corroborated the original account."),
  w("cosmopolitan", "বিশ্বজনীন, বহুসংস্কৃতিসমৃদ্ধ", "adjective", "The city has a cosmopolitan mix of cultures and cuisines."),
  w("credulous", "সহজবিশ্বাসী", "adjective", "The credulous investor fell for an obvious scam."),
  w("cryptic", "রহস্যময়, দুর্বোধ্য", "adjective", "His cryptic message left everyone confused."),
  w("culpable", "দোষী, অপরাধযোগ্য", "adjective", "The report found the company culpable for the leak."),
  w("cumbersome", "অসুবিধাজনক, ভারী", "adjective", "The old software had a cumbersome interface."),
  w("cursory", "অগভীর, তাড়াহুড়ায় করা", "adjective", "He gave the report only a cursory glance."),
  w("curtail", "সংক্ষিপ্ত করা, কমানো", "verb", "The airline had to curtail several flights due to weather."),
  w("cynical", "সন্দেহপ্রবণ, নিরাশাবাদী", "adjective", "Years of disappointment made him deeply cynical."),
  w("dearth", "অভাব, স্বল্পতা", "noun", "There is a dearth of affordable housing in the city."),
  w("debacle", "চূড়ান্ত ব্যর্থতা, বিপর্যয়", "noun", "The launch turned into a public debacle."),
  w("debilitate", "দুর্বল করে দেওয়া", "verb", "The illness debilitated him for several months."),
  w("decorum", "শালীনতা, শিষ্টাচার", "noun", "Guests were expected to maintain decorum at the ceremony."),
  w("deferential", "শ্রদ্ধাশীল, বিনীত", "adjective", "The junior staff remained deferential toward the director."),
  w("deleterious", "ক্ষতিকর", "adjective", "Smoking has a deleterious effect on lung health."),
  w("delineate", "রূপরেখা তৈরি করা, বর্ণনা করা", "verb", "The contract clearly delineates each party's duties."),
  w("demagogue", "জনতাকে খেপিয়ে তোলে এমন নেতা", "noun", "Historians warned about the rise of the demagogue."),
  w("demure", "লাজুক, বিনয়ী", "adjective", "She gave a demure smile and looked away."),
  w("denigrate", "অপমান করা, ছোট করে দেখানো", "verb", "He tried to denigrate his opponent's achievements."),
  w("deprecate", "নিন্দা করা, গুরুত্ব কমানো", "verb", "Critics deprecated the film for its weak plot."),
  w("derision", "উপহাস, বিদ্রূপ", "noun", "His idea was met with laughter and derision."),
  w("despot", "স্বৈরশাসক", "noun", "The despot ruled the country for three decades."),
  w("deter", "নিরুৎসাহিত করা, প্রতিরোধ করা", "verb", "Higher fines are meant to deter littering."),
  w("diaphanous", "স্বচ্ছ, পাতলা", "adjective", "The bride wore a diaphanous veil."),
  w("diatribe", "কঠোর সমালোচনা, তীব্র বক্তৃতা", "noun", "He launched into a diatribe against the new policy."),
  w("dichotomy", "দ্বিবিভাজন", "noun", "There is a clear dichotomy between theory and practice here."),
  w("didactic", "উপদেশমূলক, শিক্ষামূলক", "adjective", "The film felt overly didactic in its final act."),
  w("diffident", "লাজুক, আত্মবিশ্বাসহীন", "adjective", "He was too diffident to ask a question in class."),
  w("digress", "মূল বিষয় থেকে সরে যাওয়া", "verb", "The speaker began to digress from the main topic."),
  w("dilapidated", "জীর্ণ, ভগ্নদশাগ্রস্ত", "adjective", "The old mansion was left dilapidated and empty."),
  w("dilatory", "কালক্ষেপণকারী, বিলম্বকারী", "adjective", "The company used dilatory tactics to avoid paying the fine."),
  w("diligent", "পরিশ্রমী", "adjective", "A diligent student always finishes homework on time."),
  w("diminutive", "ক্ষুদ্র", "adjective", "The diminutive robot could fit in the palm of your hand."),
  w("disconcert", "বিহ্বল করা, বিভ্রান্ত করা", "verb", "The sudden question seemed to disconcert the speaker."),
  w("discordant", "অসঙ্গতিপূর্ণ, বেসুরো", "adjective", "The two reports gave discordant accounts of the same event."),
  w("discredit", "অবিশ্বাস্য করা, সুনাম নষ্ট করা", "verb", "The scandal discredited the entire committee."),
  w("disdain", "অবজ্ঞা করা", "verb", "He disdained anyone who disagreed with him."),
  w("disingenuous", "কপট, অসৎ উদ্দেশ্যপ্রণোদিত", "adjective", "It was disingenuous of him to claim he didn't know."),
  w("disparage", "অবমূল্যায়ন করা, নিন্দা করা", "verb", "She never disparages a colleague's effort in public."),
  w("disparate", "সম্পূর্ণ ভিন্ন, অসদৃশ", "adjective", "The team brought together people from disparate backgrounds."),
  w("dissemble", "গোপন করা, ভান করা", "verb", "He dissembled his true feelings behind a calm smile."),
  w("disseminate", "ছড়িয়ে দেওয়া, প্রচার করা", "verb", "The agency works to disseminate accurate health information."),
  w("dissonance", "অসঙ্গতি, বেসুর", "noun", "There was a clear dissonance between his words and actions."),
  w("distend", "ফুলে ওঠা, প্রসারিত হওয়া", "verb", "The balloon began to distend as more air was pumped in."),
  w("diverge", "ভিন্ন পথে যাওয়া, বিচ্যুত হওয়া", "verb", "Their opinions began to diverge as the meeting continued."),
  w("divulge", "প্রকাশ করা, ফাঁস করা", "verb", "She refused to divulge her source to the reporter."),
  w("dogmatic", "গোঁড়া, একগুঁয়ে মতবাদী", "adjective", "He was too dogmatic to consider another point of view."),
  w("dormant", "সুপ্ত, নিষ্ক্রিয়", "adjective", "The volcano had been dormant for over a century."),
  w("dubious", "সন্দেহজনক", "adjective", "The claim seemed dubious given the lack of evidence."),
  w("duplicity", "দ্বিচারিতা, প্রতারণা", "noun", "His duplicity was revealed when the emails surfaced."),
  w("ebullient", "উচ্ছ্বসিত, প্রাণবন্ত", "adjective", "The ebullient crowd cheered the winning goal."),
  w("eccentric", "উদ্ভট, খামখেয়ালি", "adjective", "The eccentric professor kept odd hours in his lab."),
  w("eclectic", "বিভিন্ন উৎস থেকে সংগৃহীত, মিশ্র রুচির", "adjective", "Her music collection is wonderfully eclectic."),
  w("edify", "নৈতিক বা বুদ্ধিবৃত্তিক উন্নতি করা", "verb", "The lecture was meant to edify, not just entertain."),
  w("effervescent", "প্রাণচঞ্চল, উচ্ছল", "adjective", "Her effervescent personality lit up every room."),
  w("effigy", "প্রতীকী পুতুল", "noun", "Protesters burned an effigy of the unpopular leader."),
  w("effrontery", "ধৃষ্টতা, নির্লজ্জতা", "noun", "He had the effrontery to demand a refund after breaking it."),
  w("egregious", "চরম, ঘোরতর", "adjective", "It was an egregious error that cost them the contract."),
  w("elegy", "শোকগাথা", "noun", "The poet wrote an elegy for his late father."),
  w("elicit", "বের করে আনা, প্রকাশ করানো", "verb", "The survey was designed to elicit honest feedback."),
  w("elucidate", "স্পষ্ট করে বলা, ব্যাখ্যা করা", "verb", "Could you elucidate what you mean by that term?"),
  w("elusive", "অধরা, দুষ্প্রাপ্য", "adjective", "A cure for the disease remains elusive."),
  w("emaciated", "অতিশয় শীর্ণ", "adjective", "The rescued animal was emaciated and weak."),
  w("embellish", "অলংকৃত করা, বাড়িয়ে বলা", "verb", "He tends to embellish his stories a little."),
  w("eminent", "প্রখ্যাত, বিশিষ্ট", "adjective", "An eminent scientist was invited to open the conference."),
  w("empirical", "অভিজ্ঞতালব্ধ, প্রমাণভিত্তিক", "adjective", "The theory needed empirical evidence to be accepted."),
  w("emulate", "অনুকরণ করা", "verb", "Young players often try to emulate their favorite stars."),
  w("endemic", "নির্দিষ্ট এলাকায় প্রচলিত", "adjective", "The disease is endemic to certain tropical regions."),
  w("enervate", "দুর্বল করে দেওয়া", "verb", "The extreme heat enervated the marathon runners."),
  w("engender", "সৃষ্টি করা, উদ্রেক করা", "verb", "The decision engendered a lot of public anger."),
  w("enigma", "রহস্য, ধাঁধা", "noun", "His sudden disappearance remains an enigma."),
  w("ephemeral", "ক্ষণস্থায়ী", "adjective", "Fame in this industry is often ephemeral."),
  w("epitome", "চূড়ান্ত রূপ, প্রতীক", "noun", "The old lighthouse is the epitome of the coastal town."),
  w("equanimity", "স্থিরচিত্ততা", "noun", "She faced the crisis with remarkable equanimity."),
  w("equivocal", "দ্ব্যর্থবোধক, অস্পষ্ট", "adjective", "His equivocal answer satisfied no one."),
  w("erudite", "পণ্ডিত, বিদ্বান", "adjective", "The erudite professor could discuss almost any subject."),
  w("esoteric", "গূঢ়, সীমিত জ্ঞাত", "adjective", "The seminar covered some fairly esoteric topics in physics."),
  w("espouse", "সমর্থন করা, গ্রহণ করা", "verb", "The party espouses policies focused on renewable energy."),
  w("euphemism", "মার্জিত পরিভাষা", "noun", "\"Passed away\" is a common euphemism for death."),
  w("evanescent", "ক্ষণস্থায়ী, দ্রুত মিলিয়ে যায় এমন", "adjective", "The evanescent beauty of the sunset faded within minutes."),
  w("exacerbate", "আরও খারাপ করে তোলা", "verb", "Skipping treatment can exacerbate the condition."),
  w("exculpate", "নির্দোষ প্রমাণ করা", "verb", "New evidence helped exculpate the accused man."),
  w("exigent", "জরুরি, তাৎক্ষণিক প্রয়োজনীয়", "adjective", "The team faced an exigent deadline before launch."),
  w("exonerate", "দোষমুক্ত করা", "verb", "DNA evidence exonerated him after years in prison."),
  w("expedient", "সুবিধাজনক, ব্যবহারিক", "adjective", "Taking the shortcut seemed the most expedient option."),
  w("extol", "প্রশংসা করা", "verb", "Critics extolled the director's bold new style."),
  w("extraneous", "অপ্রাসঙ্গিক, অতিরিক্ত", "adjective", "The essay was full of extraneous details."),
  w("extricate", "মুক্ত করা, উদ্ধার করা", "verb", "It took hours to extricate the car from the ditch."),
  w("exuberant", "উচ্ছল, প্রাণবন্ত", "adjective", "The children were exuberant on the last day of school."),
  w("facetious", "রসিকতাপূর্ণ, অসংগত রসিকতা করা", "adjective", "His facetious comment was not appreciated during the meeting."),
  w("fallacious", "ভ্রান্ত, যুক্তিহীন", "adjective", "The advertisement relied on a fallacious comparison."),
  w("fastidious", "খুঁতখুঁতে, খুঁতবিহীন চাহিদাসম্পন্ন", "adjective", "He is fastidious about the way his desk is arranged."),
  w("fatuous", "মূর্খতাপূর্ণ, অর্থহীন", "adjective", "It was a fatuous excuse for missing the deadline."),
  w("fawning", "তোষামোদকারী", "adjective", "The fawning assistant agreed with everything the boss said."),
  w("feckless", "অকর্মণ্য, দায়িত্বহীন", "adjective", "The feckless manager rarely finished any project on time."),
  w("fervent", "প্রবল, উৎসাহী", "adjective", "She is a fervent believer in equal education for all."),
  w("fervid", "প্রবল আবেগপূর্ণ", "adjective", "The crowd gave a fervid response to the announcement."),
  w("fetter", "শৃঙ্খলিত করা, বাধা দেওয়া", "verb", "Old regulations still fetter the growth of small businesses."),
  w("flagrant", "প্রকট, স্পষ্ট", "adjective", "It was a flagrant breach of the agreement."),
  w("flippant", "গুরুত্বহীন মনোভাবসম্পন্ন, বেপরোয়া রসিকতাপূর্ণ", "adjective", "His flippant reply annoyed the serious interviewer."),
  w("florid", "অলংকৃত, রক্তিম", "adjective", "The speech was written in a florid, old-fashioned style."),
  w("foment", "উস্কে দেওয়া, উত্তেজিত করা", "verb", "The rumors were meant to foment unrest in the city."),
  w("forbearance", "সহনশীলতা, ধৈর্য", "noun", "She showed great forbearance during the difficult negotiation."),
  w("forestall", "পূর্বেই প্রতিরোধ করা", "verb", "The company acted early to forestall any legal trouble."),
  w("fortuitous", "সৌভাগ্যবশত ঘটে যাওয়া", "adjective", "Their meeting at the airport was entirely fortuitous."),
  w("fractious", "খিটখিটে, অবাধ্য", "adjective", "The fractious committee could not agree on anything."),
  w("frugal", "মিতব্যয়ী", "adjective", "They lived a frugal life to save for their children's education."),
  w("furtive", "গোপন, চোরাগোপ্তা", "adjective", "She gave a furtive glance toward the exit."),
  w("garrulous", "বাচাল, বেশি কথা বলা", "adjective", "The garrulous taxi driver talked for the entire ride."),
  w("glib", "অনর্গল কিন্তু অগভীর কথা বলা", "adjective", "His glib excuses no longer convinced anyone."),
  w("gratuitous", "অপ্রয়োজনীয়, অহেতুক", "adjective", "The film was criticized for gratuitous violence."),
  w("gregarious", "মিশুক, সামাজিক", "adjective", "Her gregarious nature made her popular at every party."),
  w("grandiloquent", "অতিরঞ্জিত ভাষাসম্পন্ন", "adjective", "The politician's grandiloquent promises rarely came true."),
  w("guile", "ছলচাতুরী", "noun", "He achieved his goals through guile rather than honesty."),
  w("gullible", "সহজবিশ্বাসী", "adjective", "Scammers often target gullible elderly people."),
  w("hackneyed", "গতানুগতিক, বহু ব্যবহারে জীর্ণ", "adjective", "The plot relied on a hackneyed romantic ending."),
  w("hapless", "দুর্ভাগ্যপীড়িত", "adjective", "The hapless tourist lost his passport on the first day."),
  w("haughty", "উদ্ধত, অহংকারী", "adjective", "Her haughty manner made her few friends at work."),
  w("hedonist", "ভোগবাদী", "noun", "He lived like a hedonist, chasing pleasure over duty."),
  w("hegemony", "আধিপত্য", "noun", "The empire held hegemony over the entire region for centuries."),
  w("heretical", "ধর্মদ্রোহী, প্রচলিত মতের বিরুদ্ধ", "adjective", "His ideas were considered heretical at the time."),
  w("heterogeneous", "বিভিন্ন উপাদানে গঠিত, বিসদৃশ", "adjective", "The class had a heterogeneous mix of skill levels."),
  w("hidebound", "গোঁড়া, পরিবর্তনবিরোধী", "adjective", "The hidebound institution resisted every modern reform."),
  w("hyperbole", "অতিশয়োক্তি", "noun", "Saying \"I've told you a million times\" is a classic hyperbole."),
  w("hypocritical", "ভণ্ডামিপূর্ণ", "adjective", "It felt hypocritical to preach honesty while lying himself."),
  w("iconoclast", "প্রচলিত ধ্যানধারণার বিরোধী", "noun", "The artist was an iconoclast who rejected all tradition."),
  w("idiosyncrasy", "স্বকীয় বৈশিষ্ট্য", "noun", "Every writer has small idiosyncrasies in their style."),
  w("ignominious", "লজ্জাজনক, অপমানজনক", "adjective", "The team suffered an ignominious defeat at home."),
  w("illicit", "অবৈধ", "adjective", "Police shut down an illicit trading operation."),
  w("immutable", "অপরিবর্তনীয়", "adjective", "Some scientific laws are treated as immutable facts."),
  w("impartial", "নিরপেক্ষ", "adjective", "The judge is expected to remain impartial at all times."),
  w("impassive", "অবিচলিত, নির্বিকার", "adjective", "He remained impassive even as the verdict was read."),
  w("impecunious", "নিঃস্ব, অর্থহীন", "adjective", "The impecunious student survived on part-time work."),
  w("imperious", "আধিপত্যপরায়ণ, রুক্ষভাবে আদেশদানকারী", "adjective", "Her imperious tone left no room for argument."),
  w("impervious", "অভেদ্য, প্রভাবিত হয় না এমন", "adjective", "He seemed impervious to criticism from the press."),
  w("implacable", "নির্মম, দমানো যায় না এমন", "adjective", "She was an implacable opponent of the new law."),
  w("implicit", "অন্তর্নিহিত, প্রচ্ছন্ন", "adjective", "There was an implicit agreement not to discuss politics."),
  w("impromptu", "পূর্ব পরিকল্পনাহীন, তাৎক্ষণিক", "adjective", "He gave an impromptu speech after the surprise award."),
  w("impudent", "ধৃষ্ট, বেয়াদব", "adjective", "The impudent remark earned him a stern warning."),
  w("inadvertent", "অনিচ্ছাকৃত", "adjective", "It was an inadvertent mistake, not a deliberate one."),
  w("incarcerate", "কারারুদ্ধ করা", "verb", "He was incarcerated for three years for the offense."),
  w("incendiary", "উস্কানিমূলক, দাহ্য", "adjective", "The speech was seen as deeply incendiary."),
  w("incessant", "অবিরাম", "adjective", "The incessant rain flooded the streets by evening."),
  w("inchoate", "অসম্পূর্ণ, সবে শুরু হওয়া", "adjective", "The plan was still inchoate and needed more work."),
  w("incongruous", "বেমানান, অসামঞ্জস্যপূর্ণ", "adjective", "The modern statue looked incongruous next to the old temple."),
  w("inconsequential", "গুরুত্বহীন", "adjective", "The delay turned out to be entirely inconsequential."),
  w("incorrigible", "অসংশোধনীয়", "adjective", "The teacher called him an incorrigible troublemaker."),
  w("incumbent", "বর্তমান পদাধিকারী / আবশ্যিক", "adjective", "It is incumbent upon all citizens to vote responsibly."),
  w("indefatigable", "অক্লান্ত", "adjective", "Her indefatigable energy kept the whole team motivated."),
  w("indelible", "অমোচনীয়", "adjective", "The trip left an indelible memory in her mind."),
  w("indict", "অভিযুক্ত করা", "verb", "The grand jury voted to indict him on fraud charges."),
  w("indigenous", "স্থানীয়, আদিবাসী", "adjective", "The plant is indigenous to the region's wetlands."),
  w("indignant", "ক্রুদ্ধ, ক্ষুব্ধ", "adjective", "She was indignant at being blamed for someone else's error."),
  w("indolent", "অলস", "adjective", "The indolent cat slept through most of the afternoon."),
  w("ineffable", "ভাষায় প্রকাশ করা যায় না এমন", "adjective", "The view from the summit was simply ineffable."),
  w("inept", "অদক্ষ, অনভিজ্ঞ", "adjective", "His inept handling of the crisis made things worse."),
  w("inert", "নিষ্ক্রিয়, গতিহীন", "adjective", "The gas is inert and does not react with other elements."),
  w("inexorable", "অপ্রতিরোধ্য, নমনীয় নয়", "adjective", "The company faced the inexorable decline of an old industry."),
  w("ingenuous", "সরল, অকপট", "adjective", "His ingenuous question revealed his lack of experience."),
  w("inimical", "বৈরী, ক্ষতিকর", "adjective", "Such policies are inimical to small businesses."),
  w("iniquity", "অন্যায়, পাপ", "noun", "The novel exposes the iniquity of the old system."),
  w("innocuous", "নিরীহ, ক্ষতিকর নয়", "adjective", "It seemed like an innocuous question at first."),
  w("insidious", "গোপনে ক্ষতিকর, ছলনাময়", "adjective", "The disease spreads in a slow, insidious way."),
  w("insipid", "স্বাদহীন, নীরস", "adjective", "The soup was bland and insipid."),
  w("insolent", "ধৃষ্ট, অসম্মানজনক", "adjective", "The insolent reply shocked the entire classroom."),
  w("insularity", "সংকীর্ণতা, বিচ্ছিন্নতা", "noun", "Years of insularity left the town suspicious of outsiders."),
  w("intractable", "অবাধ্য, নিয়ন্ত্রণের অতীত", "adjective", "Climate change is proving to be an intractable problem."),
  w("intransigent", "আপসহীন", "adjective", "Both sides remained intransigent throughout the talks."),
  w("intrepid", "নির্ভীক, সাহসী", "adjective", "The intrepid explorer crossed the desert alone."),
  w("inundate", "প্লাবিত করা, ছেয়ে ফেলা", "verb", "The office was inundated with complaints after the outage."),
  w("inured", "অভ্যস্ত হয়ে ওঠা", "adjective", "After years on the job, he was inured to criticism."),
  w("invective", "কটূক্তি, গালিগালাজ", "noun", "The debate quickly turned into personal invective."),
  w("irascible", "খিটখিটে, বদমেজাজি", "adjective", "The irascible old man complained about everything."),
  w("irresolute", "দ্বিধাগ্রস্ত, সিদ্ধান্তহীন", "adjective", "He remained irresolute about which offer to accept."),
  w("jocular", "কৌতুকপ্রিয়", "adjective", "His jocular tone lightened the tense meeting."),
  w("jubilant", "উল্লসিত", "adjective", "The jubilant fans celebrated late into the night."),
  w("judicious", "বিচক্ষণ, বিবেচনাপ্রসূত", "adjective", "She made a judicious decision under pressure."),
  w("juxtapose", "পাশাপাশি স্থাপন করা", "verb", "The exhibit juxtaposes old photographs with modern art."),
  w("kinetic", "গতিসম্পর্কিত", "adjective", "The sculpture uses wind to create kinetic movement."),
  w("laconic", "স্বল্পভাষী", "adjective", "His laconic reply gave nothing away."),
  w("lament", "বিলাপ করা, শোক প্রকাশ করা", "verb", "She lamented the loss of the old neighborhood park."),
  w("languid", "শ্রান্ত, নিস্তেজ", "adjective", "The afternoon had a slow, languid feel to it."),
  w("largesse", "উদার দান", "noun", "The scholarship fund exists thanks to a donor's largesse."),
  w("latent", "সুপ্ত, লুক্কায়িত", "adjective", "The coach saw latent talent in the young player."),
  w("laudable", "প্রশংসনীয়", "adjective", "It was a laudable effort, even though the project failed."),
  w("lethargic", "শ্লথ, নিস্তেজ", "adjective", "The heat made everyone feel lethargic that afternoon."),
  w("levity", "লঘুতা, হালকা রসিকতা", "noun", "A little levity helped ease the tension in the room."),
  w("licentious", "লম্পট, স্বেচ্ছাচারী", "adjective", "The king was known for his licentious lifestyle."),
  w("listless", "নিস্তেজ, আগ্রহহীন", "adjective", "She felt listless after days of poor sleep."),
  w("loquacious", "বাচাল, বেশি কথা বলে এমন", "adjective", "The loquacious guide talked nonstop during the tour."),
  w("lucid", "স্পষ্ট, বোধগম্য", "adjective", "He gave a lucid explanation of a complex topic."),
  w("lugubrious", "শোকার্ত, বিষণ্ণ", "adjective", "The film has a slow, lugubrious tone throughout."),
  w("luminous", "উজ্জ্বল, দীপ্তিমান", "adjective", "The sky turned a luminous orange at sunset."),
  w("magnanimous", "উদারচেতা", "adjective", "The winner was magnanimous in victory, praising his rival."),
  w("malevolent", "হিংসাত্মক, ক্ষতিসাধনেচ্ছুক", "adjective", "The story's malevolent villain terrified young readers."),
  w("malinger", "অসুস্থতার ভান করা", "verb", "The officer suspected the soldier was malingering."),
  w("malleable", "নমনীয়, ছাঁচে ঢালা যায় এমন", "adjective", "Gold is a soft and highly malleable metal."),
  w("mandate", "আদেশ দেওয়া / আদেশ", "verb", "The new law mandates seatbelts for all passengers."),
  w("maudlin", "অতিসংবেদনশীল, কান্নাকাটিতে ভরা", "adjective", "The speech grew a little maudlin toward the end."),
  w("maverick", "স্বাধীনচেতা ব্যক্তি, প্রথাবিরোধী", "noun", "The company was founded by a maverick engineer."),
  w("mawkish", "অতিরিক্ত ভাবাবেগপূর্ণ", "adjective", "Critics found the ending mawkish and overdone."),
  w("mendacious", "মিথ্যাবাদী", "adjective", "His mendacious claims were quickly disproven."),
  w("mercurial", "খামখেয়ালি, দ্রুত মেজাজ বদলায় এমন", "adjective", "The chef was known for his mercurial temper."),
  w("meticulous", "সূক্ষ্ম, নিখুঁত", "adjective", "She kept meticulous records of every transaction."),
  w("mitigate", "প্রশমিত করা, লাঘব করা", "verb", "Insurance can help mitigate the cost of an accident."),
  w("mollify", "শান্ত করা", "verb", "The manager tried to mollify the angry customer."),
  w("morose", "বিষণ্ণ, গম্ভীর", "adjective", "He grew morose after hearing the bad news."),
  w("mundane", "সাধারণ, একঘেয়ে", "adjective", "She found the mundane office routine exhausting."),
  w("myriad", "অসংখ্য", "adjective", "The festival offers myriad activities for children."),
  w("nadir", "সর্বনিম্ন বিন্দু", "noun", "The team's loss marked the nadir of their season."),
  w("nascent", "সদ্য উদ্ভূত, সবে শুরু হওয়া", "adjective", "The nascent industry attracted a lot of early investment."),
  w("nebulous", "অস্পষ্ট, ঝাপসা", "adjective", "His plan was still nebulous and lacked detail."),
  w("nefarious", "দুষ্ট, অত্যন্ত অন্যায্য", "adjective", "The film's villain has a nefarious plan for the city."),
  w("negligent", "অবহেলাপূর্ণ", "adjective", "The driver was found negligent in the accident."),
  w("neophyte", "নবাগত, নবিশ", "noun", "As a neophyte, she asked many questions in class."),
  w("nihilism", "মূল্যবোধহীনতাবাদ", "noun", "The novel explores a character's slide into nihilism."),
  w("nostalgia", "স্মৃতিকাতরতা", "noun", "The old song filled him with nostalgia."),
  w("novice", "নবিশ, নতুন শিক্ষার্থী", "noun", "Even a novice can follow this simple recipe."),
  w("nuance", "সূক্ষ্ম পার্থক্য", "noun", "A good translator understands every nuance of meaning."),
  w("nullify", "বাতিল করা, অকার্যকর করা", "verb", "The court moved to nullify the unfair contract."),
  w("obdurate", "একগুঁয়ে, অনমনীয়", "adjective", "He remained obdurate despite everyone's advice."),
  w("obfuscate", "অস্পষ্ট করা, বিভ্রান্ত করা", "verb", "The report seemed designed to obfuscate the real numbers."),
  w("obsequious", "তোষামোদকারী", "adjective", "The obsequious waiter hovered around the famous guest."),
  w("obstinate", "একগুঁয়ে", "adjective", "The obstinate child refused to try new food."),
  w("obtuse", "স্থূলবুদ্ধি, বোঝেনা এমন", "adjective", "He seemed obtuse to the hints she was giving."),
  w("officious", "অতি হস্তক্ষেপকারী", "adjective", "The officious clerk demanded extra unnecessary paperwork."),
  w("onerous", "কষ্টসাধ্য, ভারবহুল", "adjective", "The new regulations placed an onerous burden on small shops."),
  w("opaque", "অস্বচ্ছ, দুর্বোধ্য", "adjective", "The company's pricing policy remains opaque to customers."),
  w("opulent", "বিলাসবহুল, প্রাচুর্যপূর্ণ", "adjective", "The hotel lobby had an opulent marble ceiling."),
  w("ostentatious", "জাঁকজমকপূর্ণ, আড়ম্বরপূর্ণ", "adjective", "His ostentatious display of wealth made others uneasy."),
  w("ostracize", "সমাজচ্যুত করা", "verb", "The village chose to ostracize the family after the dispute."),
  w("painstaking", "শ্রমসাধ্য, যত্নশীল", "adjective", "Restoring the mural was a painstaking process."),
  w("palliate", "লাঘব করা, প্রশমিত করা", "verb", "The treatment can palliate symptoms but not cure the disease."),
  w("paltry", "তুচ্ছ, নগণ্য", "adjective", "He received only a paltry sum for months of work."),
  w("panacea", "সর্বরোগহর ঔষধ, সর্বসমস্যার সমাধান", "noun", "Technology alone is not a panacea for poverty."),
  w("paradox", "স্ববিরোধিতা", "noun", "It's a paradox that saving fuel sometimes costs more money."),
  w("parochial", "সংকীর্ণমনা, স্থানীয়দৃষ্টিসম্পন্ন", "adjective", "His parochial views ignored global trends entirely."),
  w("parsimonious", "কৃপণ, অতি মিতব্যয়ী", "adjective", "The parsimonious manager refused to buy new equipment."),
  w("pathos", "করুণরস, সহানুভূতি জাগায় এমন গুণ", "noun", "The final scene was full of quiet pathos."),
  w("paucity", "স্বল্পতা", "noun", "There was a paucity of evidence to support the claim."),
  w("pejorative", "নিন্দাসূচক", "adjective", "The term is now considered pejorative and outdated."),
  w("penchant", "বিশেষ পছন্দ, ঝোঁক", "noun", "She has a penchant for old detective novels."),
  w("penury", "চরম দারিদ্র্য", "noun", "The family lived in penury after the factory closed."),
  w("perfidious", "বিশ্বাসঘাতক", "adjective", "History remembers him as a perfidious advisor."),
  w("perfunctory", "যান্ত্রিক, আন্তরিকতাহীন", "adjective", "He gave a perfunctory nod and walked away."),
  w("pernicious", "ক্ষতিকর, ধ্বংসাত্মক", "adjective", "Misinformation can have a pernicious effect on public health."),
  w("perspicacious", "তীক্ষ্ণদৃষ্টিসম্পন্ন", "adjective", "The perspicacious detective noticed the smallest details."),
  w("pertinacious", "একগুঁয়ে, অটল", "adjective", "Her pertinacious effort finally won her the scholarship."),
  w("petulant", "খিটখিটে, বিরক্তিপ্রবণ", "adjective", "The petulant child stomped off after losing the game."),
  w("phlegmatic", "শান্ত, অবিচলিত স্বভাবের", "adjective", "He stayed phlegmatic even during the emergency."),
  w("placate", "শান্ত করা, সন্তুষ্ট করা", "verb", "The company offered a refund to placate angry customers."),
  w("placid", "শান্ত, স্থির", "adjective", "The lake was placid in the early morning light."),
  w("platitude", "গতানুগতিক মন্তব্য", "noun", "His speech was full of platitudes and short on ideas."),
  w("plausible", "যুক্তিসঙ্গত, বিশ্বাসযোগ্য", "adjective", "She offered a plausible explanation for the delay."),
  w("plethora", "প্রাচুর্য, আধিক্য", "noun", "The market offers a plethora of choices for buyers."),
  w("pragmatic", "বাস্তববাদী", "adjective", "They took a pragmatic approach to solving the budget crisis."),
  w("precarious", "অনিশ্চিত, ঝুঁকিপূর্ণ", "adjective", "The company was in a precarious financial position."),
  w("precipitate", "তড়িঘড়ি ঘটানো / হঠকারী", "verb", "The scandal precipitated his sudden resignation."),
  w("preclude", "বাধা দেওয়া, প্রতিরোধ করা", "verb", "Bad weather may preclude an outdoor ceremony."),
  w("precocious", "বয়সের তুলনায় অগ্রসর", "adjective", "The precocious child was reading novels at age six."),
  w("predilection", "বিশেষ পছন্দ", "noun", "He has a predilection for spicy food."),
  w("prescient", "ভবিষ্যদ্‌দ্রষ্টা", "adjective", "Her prescient warning about the market proved correct."),
  w("presumptuous", "ঔদ্ধত্যপূর্ণ, অতি সাহসী", "adjective", "It felt presumptuous to ask for a raise so soon."),
  w("pretentious", "ভান করা, আড়ম্বরপূর্ণ", "adjective", "The restaurant's menu felt a bit pretentious."),
  w("prevaricate", "এড়িয়ে যাওয়া, মিথ্যা বলা", "verb", "Stop prevaricating and answer the question directly."),
  w("pristine", "অক্ষত, নির্মল", "adjective", "The beach remained pristine, far from any tourists."),
  w("probity", "সততা, ন্যায়পরায়ণতা", "noun", "Her probity earned the trust of the whole department."),
  w("proclivity", "স্বাভাবিক প্রবণতা", "noun", "He has a proclivity for taking unnecessary risks."),
  w("prodigal", "অমিতব্যয়ী, উড়নচণ্ডী", "adjective", "The prodigal son returned home after years away."),
  w("prodigious", "বিশাল, অসাধারণ", "adjective", "She has a prodigious memory for names and dates."),
  w("profligate", "অমিতব্যয়ী, স্বেচ্ছাচারী", "adjective", "His profligate spending left him deep in debt."),
  w("profound", "গভীর, তাৎপর্যপূর্ণ", "adjective", "The book had a profound effect on how she saw the world."),
  w("propensity", "স্বাভাবিক প্রবণতা", "noun", "He has a propensity to arrive late to meetings."),
  w("propitious", "শুভ, অনুকূল", "adjective", "It was a propitious time to launch the new product."),
  w("prosaic", "গদ্যময়, সাধারণ", "adjective", "The report offered a prosaic summary of the year's events."),
  w("protracted", "দীর্ঘায়িত", "adjective", "The two countries were locked in a protracted dispute."),
  w("provincial", "সংকীর্ণমনা, প্রাদেশিক", "adjective", "His provincial attitude surprised his well-traveled colleagues."),
  w("prudent", "বিচক্ষণ, সতর্ক", "adjective", "Saving part of every paycheck is a prudent habit."),
  w("pugnacious", "ঝগড়াটে, আক্রমণাত্মক", "adjective", "His pugnacious attitude often started arguments."),
  w("pundit", "বিশেষজ্ঞ, মতামত-প্রদানকারী", "noun", "Political pundits debated the election results for hours."),
  w("punctilious", "অতি সতর্ক, নিয়মনিষ্ঠ", "adjective", "She is punctilious about following every safety rule."),
  w("pusillanimous", "ভীরু, কাপুরুষোচিত", "adjective", "His pusillanimous response disappointed his supporters."),
  w("querulous", "অভিযোগপ্রবণ, খিটখিটে", "adjective", "The querulous passenger complained about every little thing."),
  w("quiescent", "নিষ্ক্রিয়, শান্ত", "adjective", "The volcano remained quiescent for many years."),
  w("quixotic", "অবাস্তব আদর্শবাদী", "adjective", "His quixotic plan to fix the economy overnight failed."),
  w("quotidian", "দৈনন্দিন, সাধারণ", "adjective", "The novel finds beauty in quotidian, everyday life."),
  w("rancor", "তিক্ততা, বিদ্বেষ", "noun", "Old rancor between the neighbors never really faded."),
  w("rapacious", "লোভী, শোষণকারী", "adjective", "The rapacious landlord raised rents every single year."),
  w("recalcitrant", "অবাধ্য", "adjective", "The recalcitrant horse refused to enter the trailer."),
  w("reciprocate", "প্রতিদান দেওয়া", "verb", "She reciprocated his kindness with a small gift."),
  w("recondite", "দুর্বোধ্য, গুঢ়", "adjective", "The paper was full of recondite mathematical terms."),
  w("redoubtable", "শক্তিশালী, ভীতিপ্রদ", "adjective", "She faced a redoubtable opponent in the final round."),
  w("refute", "খণ্ডন করা", "verb", "The scientist refuted the claim with new data."),
  w("relegate", "নিম্নপদে নামিয়ে দেওয়া, বাদ দেওয়া", "verb", "The team was relegated to the lower division this season."),
  w("remiss", "অবহেলাপূর্ণ, দায়িত্বে শিথিল", "adjective", "It would be remiss not to mention his earlier warning."),
  w("renege", "প্রতিশ্রুতি ভঙ্গ করা", "verb", "The supplier reneged on the agreed delivery date."),
  w("reprehensible", "নিন্দনীয়", "adjective", "The coach called the players' conduct reprehensible."),
  w("reprove", "তিরস্কার করা", "verb", "The teacher gently reproved the students for talking."),
  w("repudiate", "প্রত্যাখ্যান করা, অস্বীকার করা", "verb", "He repudiated the claims made against his company."),
  w("rescind", "বাতিল করা, প্রত্যাহার করা", "verb", "The board voted to rescind the earlier decision."),
  w("reticent", "স্বল্পভাষী, সংযত", "adjective", "She was reticent about discussing her personal life."),
  w("reverent", "শ্রদ্ধাশীল", "adjective", "Visitors kept a reverent silence inside the old temple."),
  w("rhetoric", "বাগ্মিতা, বাগাড়ম্বর", "noun", "His campaign relied more on rhetoric than on policy."),
  w("rife", "ব্যাপক, পূর্ণ", "adjective", "The old building was rife with structural problems."),
  w("rudimentary", "প্রাথমিক, মৌলিক", "adjective", "He only had a rudimentary understanding of the software."),
  w("ruminate", "গভীরভাবে চিন্তা করা", "verb", "She spent the evening ruminating over the day's events."),
  w("sagacious", "বিচক্ষণ, প্রাজ্ঞ", "adjective", "The sagacious advisor foresaw the risks early on."),
  w("salient", "উল্লেখযোগ্য, প্রধান", "adjective", "The report highlighted the most salient findings."),
  w("sanguine", "আশাবাদী", "adjective", "She remained sanguine about the company's future."),
  w("sardonic", "বিদ্রূপাত্মক", "adjective", "He gave a sardonic smile before answering the question."),
  w("scrupulous", "সততাপূর্ণ, নিখুঁত", "adjective", "She kept scrupulous records of every expense."),
  w("scurrilous", "অশ্লীল, অপবাদমূলক", "adjective", "The tabloid published scurrilous rumors about the actor."),
  w("sedulous", "অধ্যবসায়ী", "adjective", "His sedulous practice finally paid off in the recital."),
  w("servile", "দাসোচিত, অতি বাধ্য", "adjective", "The servile assistant never questioned a single order."),
  w("skeptic", "সংশয়বাদী", "noun", "As a skeptic, she wanted proof before believing the claim."),
  w("solicitous", "উদ্বিগ্নভাবে যত্নশীল", "adjective", "He was solicitous about his grandmother's health."),
  w("solvent", "ঋণমুক্ত, আর্থিকভাবে সচ্ছল", "adjective", "The company remained solvent despite the market crash."),
  w("sophomoric", "অপরিপক্ব, অর্ধশিক্ষিত", "adjective", "His sophomoric jokes fell flat with the older crowd."),
  w("sordid", "নোংরা, ঘৃণ্য", "adjective", "The book reveals the sordid details of the scandal."),
  w("spurious", "মিথ্যা, জাল", "adjective", "The claim turned out to be entirely spurious."),
  w("staid", "গম্ভীর, রক্ষণশীল", "adjective", "The bank had a staid, old-fashioned image."),
  w("stoic", "সংযমী, ধৈর্যশীল", "adjective", "He remained stoic throughout the painful treatment."),
  w("stolid", "নির্লিপ্ত, অনুভূতিহীন", "adjective", "The stolid guard showed no reaction to the noise."),
  w("stringent", "কঠোর", "adjective", "The factory follows stringent safety regulations."),
  w("sublime", "মহিমান্বিত, অতুলনীয়", "adjective", "The view from the peak was truly sublime."),
  w("substantiate", "প্রমাণ করা", "verb", "He could not substantiate his claim with any evidence."),
  w("subtle", "সূক্ষ্ম", "adjective", "There was a subtle change in her tone during the call."),
  w("succinct", "সংক্ষিপ্ত ও স্পষ্ট", "adjective", "Please give a succinct summary of the proposal."),
  w("superficial", "উপরিভাগের, অগভীর", "adjective", "His knowledge of the subject was only superficial."),
  w("superfluous", "অপ্রয়োজনীয়, অতিরিক্ত", "adjective", "The editor cut every superfluous word from the essay."),
  w("supplant", "স্থানচ্যুত করা, প্রতিস্থাপন করা", "verb", "Digital maps have largely supplanted printed ones."),
  w("surreptitious", "গোপন, চোরাগোপ্তা", "adjective", "He took a surreptitious look at his phone during class."),
  w("sycophant", "তোষামোদকারী", "noun", "The king was surrounded by sycophants who never disagreed."),
  w("taciturn", "স্বল্পভাষী, মৌনপ্রিয়", "adjective", "The taciturn farmer rarely spoke more than a few words."),
  w("tangential", "অপ্রাসঙ্গিক, পার্শ্বীয়", "adjective", "His comment felt tangential to the main discussion."),
  w("tantamount", "সমতুল্য", "adjective", "Silence in this case was tantamount to agreement."),
  w("temerity", "দুঃসাহস, বেপরোয়া সাহস", "noun", "She had the temerity to question the CEO in public."),
  w("tenacious", "দৃঢ়চিত্ত, ছাড়ে না এমন", "adjective", "Her tenacious effort finally solved the old case."),
  w("tenuous", "দুর্বল, ঠুনকো", "adjective", "The evidence connecting the two events was tenuous at best."),
  w("terse", "সংক্ষিপ্ত ও রূঢ়", "adjective", "He gave a terse reply and hung up the phone."),
  w("timorous", "ভীরু", "adjective", "The timorous new employee rarely spoke in meetings."),
  w("torpid", "নিস্তেজ, অলস", "adjective", "The bear grew torpid as winter approached."),
  w("tractable", "সহজে পরিচালনযোগ্য", "adjective", "The new intern proved tractable and eager to learn."),
  w("transient", "ক্ষণস্থায়ী, অস্থায়ী", "adjective", "Many workers here have transient housing arrangements."),
  w("trepidation", "শঙ্কা, ভীতি", "noun", "She approached the interview with some trepidation."),
  w("trite", "গতানুগতিক, বহুব্যবহৃত", "adjective", "The ending felt trite and predictable."),
  w("truculent", "রুক্ষ, ঝগড়াটে", "adjective", "The truculent customer shouted at the staff."),
  w("turbid", "ঘোলাটে, অস্পষ্ট", "adjective", "The river turned turbid after the heavy rain."),
  w("turgid", "স্ফীত, অতি আলংকারিক", "adjective", "The essay's turgid prose made it hard to follow."),
  w("turpitude", "নীতিভ্রষ্টতা, পাপাচার", "noun", "He was dismissed for moral turpitude."),
  w("ubiquitous", "সর্বত্র বিদ্যমান", "adjective", "Smartphones have become ubiquitous in modern life."),
  w("umbrage", "অসন্তোষ, ক্ষোভ", "noun", "She took umbrage at the careless remark."),
  w("unassuming", "নিরহংকার, সাধারণ", "adjective", "Despite his fame, he remained unassuming and polite."),
  w("unctuous", "তোষামোদপূর্ণ, কপট বিনয়ী", "adjective", "The salesman's unctuous manner made her uneasy."),
  w("undermine", "দুর্বল করা, ক্ষুণ্ণ করা", "verb", "Constant criticism began to undermine her confidence."),
  w("unfeigned", "অকৃত্রিম, সত্যিকার", "adjective", "His unfeigned joy at the news was obvious to everyone."),
  w("unprecedented", "অভূতপূর্ব", "adjective", "The flood caused unprecedented damage to the region."),
  w("unwitting", "অজ্ঞাতসারে, অনিচ্ছাকৃত", "adjective", "He became an unwitting accomplice in the scheme."),
  w("usurp", "অন্যায়ভাবে দখল করা", "verb", "The general tried to usurp power from the king."),
  w("utilitarian", "উপযোগবাদী, ব্যবহারিক", "adjective", "The building has a plain, utilitarian design."),
  w("vacillate", "দোদুল্যমান হওয়া", "verb", "He vacillated between the two job offers for weeks."),
  w("vacuous", "অন্তঃসারশূন্য, বোকা", "adjective", "The interview was full of vacuous celebrity gossip."),
  w("valedictory", "বিদায়ী", "adjective", "She gave the valedictory speech at graduation."),
  w("vapid", "নীরস, প্রাণহীন", "adjective", "The show's dialogue felt vapid and forgettable."),
  w("variegated", "বহুবর্ণ, বৈচিত্র্যময়", "adjective", "The garden was full of variegated leaves and flowers."),
  w("vehement", "প্রবল, তীব্র", "adjective", "He gave a vehement denial of the accusation."),
  w("venerate", "শ্রদ্ধা করা, পূজা করা", "verb", "The community continues to venerate its founding teacher."),
  w("veracity", "সত্যতা", "noun", "Reporters questioned the veracity of his statement."),
  w("verbose", "বাক্‌সর্বস্ব, দীর্ঘসূত্রী", "adjective", "The manual is far too verbose for a simple task."),
  w("vestige", "অবশিষ্টাংশ, চিহ্ন", "noun", "Only a vestige of the old fort remains today."),
  w("vex", "বিরক্ত করা", "verb", "The constant noise from the street vexed the residents."),
  w("vicarious", "পরোক্ষ, অন্যের মাধ্যমে অনুভূত", "adjective", "He gets vicarious pleasure from watching his students succeed."),
  w("vigilant", "সতর্ক", "adjective", "Guards remained vigilant throughout the night."),
  w("vilify", "অপবাদ দেওয়া, নিন্দা করা", "verb", "The press unfairly vilified the young athlete."),
  w("vindicate", "নির্দোষ প্রমাণ করা, সমর্থন করা", "verb", "The later results vindicated her original theory."),
  w("vindictive", "প্রতিহিংসাপরায়ণ", "adjective", "His vindictive response surprised everyone at the office."),
  w("virulent", "মারাত্মক, তীব্র বিষাক্ত", "adjective", "A virulent strain of the virus spread quickly."),
  w("viscous", "সান্দ্র, ঘন", "adjective", "The honey was too viscous to pour easily."),
  w("vitriolic", "তীব্র বিষাক্ত সমালোচনামূলক", "adjective", "The review was surprisingly vitriolic for such a small mistake."),
  w("vociferous", "উচ্চকণ্ঠ, সোচ্চার", "adjective", "A vociferous group of fans protested outside the stadium."),
  w("volatile", "অস্থির, পরিবর্তনশীল", "adjective", "The stock market has been extremely volatile this month."),
  w("wanton", "বেপরোয়া, স্বেচ্ছাচারী", "adjective", "The report described wanton destruction of the forest."),
  w("wary", "সতর্ক, সাবধান", "adjective", "She stayed wary of strangers offering easy money."),
  w("whimsical", "খামখেয়ালি, মজাদার কল্পনাপূর্ণ", "adjective", "The story has a whimsical, dreamlike quality."),
  w("wistful", "আকাঙ্ক্ষাপূর্ণ, বিষাদমাখা স্মৃতিকাতর", "adjective", "She gave a wistful smile thinking of her hometown."),
  w("wry", "শুষ্ক রসিকতাপূর্ণ, বাঁকা", "adjective", "He made a wry comment about the delayed train."),
  w("zealot", "গোঁড়া উৎসাহী ব্যক্তি", "noun", "The movement attracted more than a few zealots."),
  w("zenith", "চরম বিন্দু, শীর্ষবিন্দু", "noun", "The empire reached its zenith in the third century."),
];

export function gre500Words() {
  const now = Date.now();
  return GRE_500.map((s, i) => makeWord(s, now - i));
}
