/**
 * Builds a lib/data/<name>.ts deck file from a plain word list.
 *
 * Input (scripts/data/<name>.words.txt): one word per line, `english|bangla|pos`
 * (pos: n, v, adj, or adv). No sentences needed — this script generates the
 * simple / compound / complex example sentences for you.
 *
 * Usage:
 *   npx tsx scripts/build-deck.ts gre-iba "GRE / IBA"
 *   npx tsx scripts/build-deck.ts words-1000 "1000 Words"
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { generateSentences, type Pos } from "./sentence-templates";

const [, , name, label] = process.argv;
if (!name) {
  console.error("Usage: npx tsx scripts/build-deck.ts <deck-name> [label]");
  process.exit(1);
}

const inputPath = join(__dirname, "data", `${name}.words.txt`);
const outputPath = join(__dirname, "..", "lib", "data", `${name}.ts`);
const constName = name.replace(/[^a-zA-Z0-9]/g, "_").toUpperCase() + "_RAW";

const raw = readFileSync(inputPath, "utf-8");
const lines = raw
  .split("\n")
  .map((l) => l.trim())
  .filter(Boolean);

const out: string[] = [];
let skipped = 0;

for (const line of lines) {
  const [english, bangla, pos] = line.split("|").map((s) => (s ?? "").trim());
  if (!english || !bangla) {
    skipped++;
    continue;
  }
  const { simple, compound, complex: complexSentence } = generateSentences(english, (pos as Pos) || "n");
  out.push(`${english}|${bangla}|${pos || ""}|${simple}|${compound}|${complexSentence}`);
}

const header =
  `/**\n` +
  ` * ${label ?? name} word list. Generated by scripts/build-deck.ts from\n` +
  ` * scripts/data/${name}.words.txt — do not hand-edit sentence text here for\n` +
  ` * more than a word or two; fix the templates or the source list instead.\n` +
  ` * One word per line:\n` +
  ` *   english|bangla|pos|simple sentence|compound sentence|complex sentence\n` +
  ` * pos: n = noun, v = verb, adj = adjective, adv = adverb.\n` +
  ` */\n`;

const body = header + `export const ${constName} = \`\n` + out.join("\n") + "\n`;\n";

writeFileSync(outputPath, body, "utf-8");
console.log(`Wrote ${out.length} words to ${outputPath} (skipped ${skipped}).`);
